package v1

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// export VERSION=`git describe --tags --always`
// export DATE=`date -u '+%Y-%m-%d_%I:%M:%S%p-GMT'`
// export COMMIT_HASH=`git rev-parse HEAD`

// go build -a -ldflags "-X github.com/prabhatsharma/zinc/pkg/meta/v1.AppVersion=$VERSION" -o zinc
var (
	// AppVersion is the version of the program - Git tag - git describe --tags --always
	AppVersion = "v0.0.0"
	// GoVersion is the build number of the program as generated by the CI system
	GoVersion = "0"
	// GitCommit is the commit hash of the program - git rev-parse HEAD
	GitCommit = "0"
	// BuildTime is the date of the build - date -u '+%Y-%m-%d_%I:%M:%S%p-GMT'
	BuildTime = "0"
)

// GetVersion returns the version of the program
func GetVersion(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"AppVersion": AppVersion,
		"GoVersion":  GoVersion,
		"GitCommit":  GitCommit,
		"BuildTime":  BuildTime,
	})
}
